<?php
# Enable Error Reporting and Display:
error_reporting(~0);
ini_set('display_errors', 1);

$getUrlParameters = get_query_string();
$urlStaticApiUrl = 'http://api.tvmaze.com/search/shows?q='.$getUrlParameters;

$json = file_get_contents($urlStaticApiUrl);
$returnedValues = json_decode($json, TRUE);

//Assign to an array names and scores
for ($x = 0; $x < count($returnedValues); $x++) {
    $arrayTotal["name"][$x] = $returnedValues[$x]['show']['name'];
    $arrayTotal["score"][$x] = $returnedValues[$x]['score'];
}

//Counter for score loop
$counter = 0;

//Array to filter non type get values
foreach ($arrayTotal['name'] as $valueName) {
    $valueBack = foundStringCaseInsensitive($valueName, $_GET['q']);
    if ($valueBack != null) {
        $finalArrayName[$valueName] = $valueBack;
        $finalArrayScore[$valueName] = $arrayTotal['score'][$counter];
        echo " Name: ".$finalArrayName[$valueName]." - Score: ".$finalArrayScore[$valueName];
        echo "<br/>";
    }
    $counter++;
}

function foundStringCaseInsensitive($fullString, $searchString)
{
    $positionFound = strripos($fullString, $searchString);
    if (is_int($positionFound)) {
        return $fullString;
    }
}

function get_query_string(){
    $firstQuery = explode("=",$_SERVER['QUERY_STRING']);
    $arguments = explode("&",$_SERVER['QUERY_STRING']);

    if (count($arguments) > 1 OR $firstQuery[0] != 'q'){
        echo "invalid response";
        exit;
    }else{
    return $_GET['q'];
    }

}